spring:
  application:
    name: StreetWalekrUserService
  datasource:
    url: jdbc:postgresql://localhost:5434/homerep_userservice
    username: "postgres"
    password: "postgres"
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          time_zone: Europe/Moscow
server:
  port: 8083

grpc:
  client:
    location-service:
      address: static://localhost:50051
      negotiation-type: plaintext

