spring:
  application:
    name: StreetWalkerUserService
  datasource:
    url: jdbc:postgresql://127.0.0.1:5433/streetwalker_auth
    username: "postgres"
    password: "postgres"
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          time_zone: Europe/Moscow
  jackson:
    default-property-inclusion: non_null
server:
  port: 8083

grpc:
  client:
    location-service:
      address: static://localhost:50051
      negotiation-type: plaintext
walker:
  secret: "yo78$$dontCrackPleaseASdujisdufasbasu"
  lifetime: 600000
