package streetwalker.userservice.models.security;


public enum ActionType {
    LOGIN,
    LOGOUT,
    SIGNUP,
    UPDATE_PASSWORD,
    DELETE_ACCOUNT,
    PROFILE_UPDATE,
    EMAIL_VERIFICATION,
    PASSWORD_RESET_REQUEST,
    REFRESH_TOKEN,
    SEARCH,
    ADD_FRIEND,
    REMOVE_FRIEND,
    VIEW_FRIENDS,
    VIEW_MUTUAL_FRIENDS,
    SEARCH_FRIENDS,
    VIEW_FRIEND_SUGGESTIONS
}